// <auto-generated />
namespace MediCaps.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class unab : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(unab));
        
        string IMigrationMetadata.Id
        {
            get { return "202106231702179_unab"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
