// <auto-generated />
namespace MediCaps.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedusertypeinlogin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedusertypeinlogin));
        
        string IMigrationMetadata.Id
        {
            get { return "202106140951502_added usertype in login "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
