// <auto-generated />
namespace MediCaps.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MedicineTablecreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MedicineTablecreated));
        
        string IMigrationMetadata.Id
        {
            get { return "202106140440056_Medicine Table created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
